version: 2
jobs:
  build:
    docker:
        - image: byuoitav/build-env:master

    working_directory: /go/src/github.com/byuoitav/authmiddleware

    steps:
        - checkout
        - run: rm -r ~/.gradle || true
        - run: go test -v -race $(go list ./... | grep -v /vendor/)