version: 2
jobs:
  build:
    docker:
        - image: byuoitav/build-env:master

    working_directory: /go/src/github.com/byuoitav/authmiddleware

    steps:
        - checkout
        - run: gvt fetch -branch $CIRCLE_BRANCH github.com/byuoitav/common
